[phases.setup]
nixPkgs = [
    "php",
    "php83Extensions.pdo",
    "php83Extensions.pdo_mysql",
    "php83Extensions.curl",
    "php83Extensions.mbstring",
    "php83Extensions.session",
    "php83Extensions.json"
]

[start]
cmd = "frankenphp run --config /app/Caddyfile"
